/**
 * 耙耳朵麻将馆 - 麻将玩法配置
 * 各派系核心参数定义
 */

const MAHJONG_VARIANTS = {
  sichuan: {
    id: 'sichuan',
    name: '四川麻将',
    subtitle: '血战到底',
    icon: '🌶️',
    description: '四川重庆地区最流行，缺门、血战到底、刮风下雨',
    tileCount: 108,
    hasWindTiles: false,
    hasDragonTiles: false,
    hasFlowerTiles: false,
    handSize: 13,
    dealerHandSize: 14,
    canChow: false,
    canPung: true,
    canKong: true,
    mustMissingSuit: true,
    bloodShed: true, // 血战到底
    minFan: 0,
    maxFan: 8,
    baseScore: 10,
    specialRules: ['最后四张自动胡', '一炮多响', '查花猪查大叫'],
    fanTypes: ['平胡', '对对胡', '清一色', '七对', '龙七对', '带幺九', '清对', '将对', '杠上花', '杠上炮', '抢杠胡', '海底捞月', '根'],
  },

  guobiao: {
    id: 'guobiao',
    name: '国标麻将',
    subtitle: '8番起和',
    icon: '🏆',
    description: '国家体育总局制定，国际竞赛标准，81种番种，8番起和',
    tileCount: 144,
    hasWindTiles: true,
    hasDragonTiles: true,
    hasFlowerTiles: true,
    handSize: 13,
    dealerHandSize: 14,
    canChow: true,
    canPung: true,
    canKong: true,
    mustMissingSuit: false,
    bloodShed: false,
    minFan: 8,
    maxFan: 88,
    baseScore: 1,
    specialRules: ['花牌可打出', '无底牌摸到底流局', '四圈16局赛制'],
    fanTypes: ['88番:大四喜/大三元/十三幺/九莲宝灯/四杠/连七对/绿一色', '64番:字一色/小四喜/小三元/四暗刻', '48番:一色四同顺/一色四节高', '32番:一色四步高/三杠/混幺九', '24番:七对/七星不靠/全双刻/清一色', '16番:清龙/三色双龙会/三暗刻', '12番:全不靠/组合龙/大于五/小于五', '8番:花龙/推不倒/三色三同顺/无番胡/碰碰胡/混一色/妙手回春/海底捞月/杠上开花/抢杠胡'],
  },

  guangdong_jipinghu: {
    id: 'guangdong_jipinghu',
    name: '广东麻将',
    subtitle: '鸡平胡',
    icon: '🥟',
    description: '珠三角最主流，鸡胡0番、平胡1番、爆胡3番封顶',
    tileCount: 136,
    hasWindTiles: true,
    hasDragonTiles: true,
    hasFlowerTiles: false,
    handSize: 13,
    dealerHandSize: 14,
    canChow: true,
    canPung: true,
    canKong: true,
    mustMissingSuit: false,
    bloodShed: false,
    minFan: 0,
    maxFan: 3,
    baseScore: 10,
    specialRules: ['起和番数', '四归西流局', '四杠流局', '十三幺可突破封顶'],
    fanTypes: ['鸡胡(0番)', '平胡(1番)', '对对胡(2番)', '混一色(2番)', '清一色(3番)', '大三元(3番)', '大四喜(3番)', '杠上开花(+1)', '海底捞月(+1)'],
  },

  guangdong_tuidaohu: {
    id: 'guangdong_tuidaohu',
    name: '广东麻将',
    subtitle: '推倒胡',
    icon: '🏙️',
    description: '深圳等移民城市流行，只能碰杠不能吃，不计算番数',
    tileCount: 136,
    hasWindTiles: true,
    hasDragonTiles: true,
    hasFlowerTiles: false,
    handSize: 13,
    dealerHandSize: 14,
    canChow: false,
    canPung: true,
    canKong: true,
    mustMissingSuit: false,
    bloodShed: false,
    minFan: 0,
    maxFan: 0,
    baseScore: 10,
    specialRules: ['只分大胡小胡', '无爆胡封顶', '只能碰杠不能吃'],
    fanTypes: ['小胡(基本胡)', '大胡(对对胡/清一色/七对/大三元/大四喜等)'],
  },

  changsha: {
    id: 'changsha',
    name: '长沙麻将',
    subtitle: '扎鸟加倍',
    icon: '🌶️',
    description: '湖南流行，四喜/板板胡/六六顺/缺一色起手胡，扎鸟加倍',
    tileCount: 108,
    hasWindTiles: false,
    hasDragonTiles: false,
    hasFlowerTiles: false,
    handSize: 13,
    dealerHandSize: 14,
    canChow: true,
    canPung: true,
    canKong: true,
    mustMissingSuit: true,
    bloodShed: false,
    minFan: 0,
    maxFan: 8,
    baseScore: 10,
    specialRules: ['扎鸟加倍', '四喜起手胡', '板板胡起手胡', '六六顺起手胡', '缺一色起手胡'],
    fanTypes: ['平胡', '对对胡', '清一色', '七对', '龙七对', '将将胡', '海底捞月', '杠上开花'],
  },

  shanghai: {
    id: 'shanghai',
    name: '上海麻将',
    subtitle: '花分勒子',
    icon: '🏙️',
    description: '上海流行，碰碰胡及以上才能和，花分勒子，5勒子封顶',
    tileCount: 144,
    hasWindTiles: true,
    hasDragonTiles: true,
    hasFlowerTiles: true,
    handSize: 13,
    dealerHandSize: 14,
    canChow: true,
    canPung: true,
    canKong: true,
    mustMissingSuit: false,
    bloodShed: false,
    minFan: 0,
    maxFan: 5,
    baseScore: 1,
    specialRules: ['碰碰胡起和', '花分计算', '勒子封顶', '抓满8花直接胡'],
    fanTypes: ['碰碰胡(1勒)', '混一色(1勒)', '清一色(2勒)', '混碰(2勒)', '清碰(3勒)', '字一色(4勒)', '八花齐(2勒)'],
  },

  dongbei: {
    id: 'dongbei',
    name: '东北麻将',
    subtitle: '先打后抓',
    icon: '❄️',
    description: '东北流行，先打后抓，宝牌万能，必须有顺有刻有幺九',
    tileCount: 136,
    hasWindTiles: true,
    hasDragonTiles: true,
    hasFlowerTiles: false,
    handSize: 13,
    dealerHandSize: 14,
    canChow: true,
    canPung: true,
    canKong: true,
    mustMissingSuit: false,
    bloodShed: false,
    minFan: 0,
    maxFan: 8,
    baseScore: 10,
    specialRules: ['先打后抓', '宝牌万能', '必须有顺有刻', '必须有幺九', '清一色不能单独胡', '宝中宝最高番'],
    fanTypes: ['平胡', '夹胡', '对对胡', '清一色(需带字)', '七对', '宝中宝', '杠上开花'],
  },

  taiwan: {
    id: 'taiwan',
    name: '台湾麻将',
    subtitle: '16张眼牌',
    icon: '🏝️',
    description: '台湾流行，16张牌制，眼牌规则，拦和优先权',
    tileCount: 144,
    hasWindTiles: true,
    hasDragonTiles: true,
    hasFlowerTiles: true,
    handSize: 16,
    dealerHandSize: 16,
    canChow: true,
    canPung: true,
    canKong: true,
    mustMissingSuit: false,
    bloodShed: false,
    minFan: 0,
    maxFan: 16,
    baseScore: 10,
    specialRules: ['16张牌(5组+1将)', '眼牌可看暗杠', '连庄加番', '拦和优先权', '花牌影响番数'],
    fanTypes: ['平胡', '门清', '断幺九', '平和', '对对胡', '混一色', '清一色', '大三元', '大四喜', '字一色', '七对', '十三幺', '杠上开花', '海底捞月'],
  },

  hongkong: {
    id: 'hongkong',
    name: '香港麻将',
    subtitle: '三番起和',
    icon: '🏙️',
    description: '香港流行，三番起和，三三制计番，十三番封顶',
    tileCount: 136,
    hasWindTiles: true,
    hasDragonTiles: true,
    hasFlowerTiles: false,
    handSize: 13,
    dealerHandSize: 14,
    canChow: true,
    canPung: true,
    canKong: true,
    mustMissingSuit: false,
    bloodShed: false,
    minFan: 3,
    maxFan: 13,
    baseScore: 10,
    specialRules: ['三番起和', '三三制计番', '十三番封顶', '屁和(无番可和)', '花牌按方位计番'],
    fanTypes: ['平胡(1番)', '门清(1番)', '断幺(1番)', '平和(1番)', '对对胡(3番)', '混一色(3番)', '小三元(3番)', '清一色(7番)', '大三元(13番)', '大四喜(13番)', '十三幺(13番)', '字一色(13番)'],
  },
};

// 获取玩法列表（用于前端展示）
function getVariantList() {
  return Object.values(MAHJONG_VARIANTS).map(v => ({
    id: v.id,
    name: v.name,
    subtitle: v.subtitle,
    icon: v.icon,
    description: v.description,
    tileCount: v.tileCount,
    minFan: v.minFan,
    maxFan: v.maxFan,
  }));
}

// 获取玩法配置
function getVariant(id) {
  return MAHJONG_VARIANTS[id] || MAHJONG_VARIANTS.sichuan;
}

module.exports = {
  MAHJONG_VARIANTS,
  getVariantList,
  getVariant,
};
